// <auto-generated />
namespace Afas.ImportConverter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _00001AfasImportConverter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00001AfasImportConverter));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061820191_00001-Afas-ImportConverter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
