// <auto-generated />
namespace Afas.AfComply.Reporting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _00010AfasAFcomply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00010AfasAFcomply));
        
        string IMigrationMetadata.Id
        {
            get { return "201801312210428_00010-Afas-AFcomply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
