//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approved1094FinalPart3
    {
        public long Approved1094FinalPart3Id { get; set; }
        public long Approved1094FinalPart1Id { get; set; }
        public int MonthId { get; set; }
        public bool MinimumEssentialCoverageOfferIndicator { get; set; }
        public int FullTimeEmployeeCount { get; set; }
        public int TotalEmployeeCount { get; set; }
        public bool AggregatedGroupIndicator { get; set; }
        public System.Guid ResourceId { get; set; }
        public int EntityStatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
