//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerTaxYearTransmissionStatu
    {
        public long EmployerTaxYearTransmissionStatusId { get; set; }
        public long EmployerTaxYearTransmissionId { get; set; }
        public int TransmissionStatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid ResourceId { get; set; }
        public int EntityStatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual EmployerTaxYearTransmission EmployerTaxYearTransmission { get; set; }
    }
}
