//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMeasurementAverageHour
    {
        public long EmployeeMeasurementAverageHoursId { get; set; }
        public int EmployeeId { get; set; }
        public int MeasurementId { get; set; }
        public Nullable<decimal> WeeklyAverageHours { get; set; }
        public Nullable<decimal> MonthlyAverageHours { get; set; }
        public System.Guid ResourceId { get; set; }
        public int EntityStatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsNewHire { get; set; }
        public Nullable<decimal> TrendingWeeklyAverageHours { get; set; }
        public Nullable<decimal> TrendingMonthlyAverageHours { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
