//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance_contribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insurance_contribution()
        {
            this.employee_insurance_offer = new HashSet<employee_insurance_offer>();
        }
    
        public int ins_cont_id { get; set; }
        public int insurance_id { get; set; }
        public string contribution_id { get; set; }
        public int classification_id { get; set; }
        public decimal amount { get; set; }
        public string modBy { get; set; }
        public Nullable<System.DateTime> modOn { get; set; }
        public string history { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_insurance_offer> employee_insurance_offer { get; set; }
        public virtual insurance insurance { get; set; }
    }
}
