//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcaEntities : DbContext
    {
        public AcaEntities()
            : base("name=AcaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee_dependents> employee_dependents { get; set; }
        public virtual DbSet<employee_insurance_offer> employee_insurance_offer { get; set; }
        public virtual DbSet<EmployeeMeasurementAverageHour> EmployeeMeasurementAverageHours { get; set; }
        public virtual DbSet<employer> employers { get; set; }
        public virtual DbSet<insurance_carrier> insurance_carrier { get; set; }
        public virtual DbSet<insurance_contribution> insurance_contribution { get; set; }
        public virtual DbSet<insurance_coverage> insurance_coverage { get; set; }
        public virtual DbSet<insurance_coverage_editable> insurance_coverage_editable { get; set; }
        public virtual DbSet<plan_year> plan_year { get; set; }
        public virtual DbSet<View_air_replacement_employee_monthly_detail> View_air_replacement_employee_monthly_detail { get; set; }
        public virtual DbSet<View_insurance_change_events> View_insurance_change_events { get; set; }
        public virtual DbSet<View_insurance_change_events_details> View_insurance_change_events_details { get; set; }
        public virtual DbSet<View_air_replacement_PartIII_details> View_air_replacement_PartIII_details { get; set; }
        public virtual DbSet<View_full_insurance_coverage> View_full_insurance_coverage { get; set; }
        public virtual DbSet<View_air_replacement_EmployeeMonthlyDetailsPreFiltered> View_air_replacement_EmployeeMonthlyDetailsPreFiltered { get; set; }
        public virtual DbSet<View_air_replacement_EmployeeYearlyDetails> View_air_replacement_EmployeeYearlyDetails { get; set; }
        public virtual DbSet<insurance> insurances { get; set; }
        public virtual DbSet<View_1094Part1> View_1094Part1 { get; set; }
        public virtual DbSet<View_1094Part4> View_1094Part4 { get; set; }
        public virtual DbSet<View_1094Part3> View_1094Part3 { get; set; }
        public virtual DbSet<View_1094Part2> View_1094Part2 { get; set; }
        public virtual DbSet<EmployerTaxYearTransmissionStatu> EmployerTaxYearTransmissionStatus { get; set; }
        public virtual DbSet<EmployerTaxYearTransmission> EmployerTaxYearTransmissions { get; set; }
    }
}
