//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_air_replacement_EmployeeMonthlyDetailsPreFiltered
    {
        public Nullable<int> EmployeeId { get; set; }
        public int plan_year_id { get; set; }
        public int MeasurementId { get; set; }
        public Nullable<decimal> WeeklyAverageHours { get; set; }
        public Nullable<decimal> MonthlyAverageHours { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public System.DateTime stability_start { get; set; }
        public System.DateTime stability_end { get; set; }
        public bool IsNewHire { get; set; }
        public Nullable<int> employee_type_id { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public Nullable<System.DateTime> initialMeasurmentEnd { get; set; }
        public Nullable<int> classification_id { get; set; }
        public Nullable<int> aca_status_id { get; set; }
        public int insurance_id { get; set; }
        public int ins_cont_id { get; set; }
        public Nullable<bool> offered { get; set; }
        public Nullable<int> offeredOn { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<int> acceptedOn { get; set; }
        public Nullable<int> effectiveDate { get; set; }
        public decimal hra_flex_contribution { get; set; }
        public Nullable<int> contribution_id { get; set; }
        public decimal amount { get; set; }
        public decimal monthlycost { get; set; }
        public Nullable<bool> minValue { get; set; }
        public Nullable<bool> offSpouse { get; set; }
        public Nullable<bool> offDependent { get; set; }
        public int insurance_type_id { get; set; }
        public Nullable<bool> Mec { get; set; }
        public Nullable<bool> SpouseConditional { get; set; }
        public Nullable<bool> fullyPlusSelfInsured { get; set; }
        public int month_id { get; set; }
        public string name { get; set; }
        public Nullable<int> employer_id { get; set; }
        public string ash_code { get; set; }
        public Nullable<int> WaitingPeriodID { get; set; }
        public string Ooc { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public Nullable<int> InitialStabilityPeriodMonths { get; set; }
        public Nullable<System.DateTime> InitialStabilityPeriodEndDate { get; set; }
    }
}
