//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_insurance_change_events_details
    {
        public int rowid { get; set; }
        public int employee_id { get; set; }
        public int plan_year_id { get; set; }
        public Nullable<int> employer_id { get; set; }
        public Nullable<int> insurance_id { get; set; }
        public Nullable<int> ins_cont_id { get; set; }
        public Nullable<bool> offered { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<decimal> hra_flex_contribution { get; set; }
        public Nullable<decimal> EmployerContribution { get; set; }
        public string EmployerContributionType { get; set; }
        public Nullable<decimal> monthlycost { get; set; }
        public Nullable<bool> minValue { get; set; }
        public Nullable<bool> offSpouse { get; set; }
        public Nullable<bool> offDependent { get; set; }
        public Nullable<int> insurance_type_id { get; set; }
        public Nullable<bool> SpouseConditional { get; set; }
        public Nullable<bool> Mec { get; set; }
        public Nullable<bool> fullyPlusSelfInsured { get; set; }
        public long UniqueRowID { get; set; }
    }
}
