//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_air_replacement_employee_monthly_detail
    {
        public Nullable<long> EmployeeMotnhlyDetailID { get; set; }
        public Nullable<int> employer_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public Nullable<int> aca_status_id { get; set; }
        public Nullable<int> classification_id { get; set; }
        public int month_id { get; set; }
        public Nullable<decimal> MonthlyAverageHours { get; set; }
        public string DefaultOfferOfCoverage { get; set; }
        public Nullable<bool> Mec { get; set; }
        public string DefaultSafeHarborCode { get; set; }
        public Nullable<decimal> EmployeesMonthlyCost { get; set; }
        public Nullable<bool> EmployeeOfferedCoverage { get; set; }
        public Nullable<bool> EmployeeEnrolledInCoverage { get; set; }
        public Nullable<int> InsuranceType { get; set; }
        public Nullable<bool> OfferedToSpouse { get; set; }
        public Nullable<bool> OfferedToSpouseConditional { get; set; }
        public Nullable<bool> OfferedToDependent { get; set; }
        public int Mainland { get; set; }
        public Nullable<System.DateTime> CoverageEffectiveDate { get; set; }
        public Nullable<bool> fullyPlusSelfInsured { get; set; }
        public Nullable<bool> minValue { get; set; }
        public Nullable<int> WaitingPeriodID { get; set; }
        public int TaxYear { get; set; }
        public Nullable<int> plan_year_id { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
    }
}
