//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1094Part2
    {
        public int employer_id { get; set; }
        public int tax_year { get; set; }
        public Nullable<bool> IsAle { get; set; }
        public Nullable<int> Form1095Count { get; set; }
    }
}
