//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afas.AfComply.Reporting.Domain.LegacyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_air_replacement_EmployeeYearlyDetails
    {
        public int EmployeeId { get; set; }
        public int plan_year_id { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<decimal> WeeklyAverageHours { get; set; }
        public Nullable<decimal> MonthlyAverageHours { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public System.DateTime stability_start { get; set; }
        public System.DateTime stability_end { get; set; }
        public Nullable<bool> IsNewHire { get; set; }
        public int employee_type_id { get; set; }
        public Nullable<System.DateTime> terminationDate { get; set; }
        public System.DateTime initialMeasurmentEnd { get; set; }
        public Nullable<int> classification_id { get; set; }
        public Nullable<int> aca_status_id { get; set; }
        public int employer_id { get; set; }
        public string ash_code { get; set; }
        public Nullable<int> WaitingPeriodID { get; set; }
        public string Ooc { get; set; }
        public System.DateTime hireDate { get; set; }
        public Nullable<int> InitialStabilityPeriodMonths { get; set; }
        public Nullable<System.DateTime> InitialStabilityPeriodEndDate { get; set; }
        public int tax_year { get; set; }
    }
}
