export const environment = {
  production: false,
  canShowDetailedErrorMessages: true,
  Feature:
  {
      IrsInstructionsLink: "Feature.IrsInstructionsLink",
      IrsInstructionsLink2017: "Feature.IrsInstructionsLink2017",
      IrsInstructionsPDFLink: "#{Feature.IrsInstructionsPDFLink}",
      QlikEnabled: "Feature.QlikEnabled",
      AutoLogoutTime: "Feature.AutoLogoutTime",
      BulkBatchSize: "Feature.BulkBatchSize",
      CurrentReportingYear: "2019",
      DOBDefaultValueEnabled: "Feature.DOBDefaultValueEnabled",
      EmployeeDemographicEmployeeNumberRequired: "Feature.EmployeeDemographicEmployeeNumberRequired",
      EmployeeDemographicGenerateEmployeeNumberEnabled: "Feature.EmployeeDemographicGenerateEmployeeNumberEnabled",
      EmployeeExportCarrierFileEnabled: "Feature.EmployeeExportCarrierFileEnabled",
      EmployeeExportOfferFileEnabled: "Feature.EmployeeExportOfferFileEnabled",
      ETLProcess: "Feature.ETLProcess",
      FastCalculationEnabled: "Feature.FastCalculationEnabled",
      HomePageExternalLink: "Feature.HomePageExternalLink",
      GuidePageExternalLink: "Feature.GuidePageExternalLink",
      HomePageExternalMessage: "Feature.HomePageExternalMessage",
      HomePageMessage: "Feature.HomePageMessage",
      HomePageMessageEnabled: "Feature.HomePageMessageEnabled",
      HomePageMessageLink: "Feature.HomePageMessageLink",
      HomePageMessageLong: "Feature.HomePageMessageLong",
      LimitCalculationBatches: "Feature.LimitCalculationBatches",
      PrintPdfDropPath: "Feature.PrintPdfDropPath",
      QlikHomeMashup: "Feature.QlikHomeMashup",
      ShowDOB: "Feature.ShowDOB",
      StoreLocation: "Feature.StoreLocation",
      Unfinalize: "Feature.Unfinalize",
  },
  Branding:
  {
      IrsDeadlineCertify:"Branding.IrsDeadlineCertify",
      IrsDeadlineSetup:"Branding.IrsDeadlineSetup",
      ProductName: "Branding.ProductName",
      AutoLogoutMessage: "Your Session has expired.",
      CompanyShortName: "CI",
      AddressCityState: "Branding.AddressCityState",
      CompanyName: "Branding.CompanyName",
      CompanyWebSite: "Branding.CompanyWebSite",
      CopyrightYears: "Branding.CopyrightYears",
      IrsDeadlineTransmit: "Branding.IrsDeadlineTransmit",
      IrsReprintFeeEnabled: "Branding.IrsReprintFeeEnabled",
      Irs1094Enabled: "Branding.Irs1094Enabled",
      LogoUri: "Branding.LogoUri",
      PhoneNumber: "Branding.PhoneNumber"
  }
};
